import type { CategorySlug } from "@/types";

export const AI_DISCLAIMERS: Record<CategorySlug, string> = {
  legal:
    "AI analysis only. This does not constitute legal advice. Always consult a qualified attorney for legal matters.",
  business:
    "AI analysis only. This does not constitute legal or financial advice. Always verify important business decisions with a qualified professional.",
};

const DISCLAIMER_PATTERNS = [
  /\s*(?:⚠️?\s*)?This analysis is generated by AI for informational purposes only and does not constitute legal advice\. Always consult a qualified attorney for legal matters\.?\s*$/i,
  /\s*(?:⚠️?\s*)?This analysis is AI-generated for informational purposes only and does not constitute legal or financial advice\. Always consult a qualified professional for important business decisions\.?\s*$/i,
];

export function stripAiDisclaimer(content: string) {
  return DISCLAIMER_PATTERNS.reduce((answer, pattern) => answer.replace(pattern, ""), content).trim();
}
