import { getDocumentRequestContext } from "@/lib/documents/server";
import { listCreemCustomerTransactions } from "@/lib/creem/client";
import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function formatDate(value?: number | string) {
  if (!value) return "Unknown";

  const date =
    typeof value === "number"
      ? new Date(value > 10_000_000_000 ? value : value * 1000)
      : new Date(value);

  if (Number.isNaN(date.getTime())) return "Unknown";

  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(date);
}

function formatAmount(amount?: number, currency = "USD") {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency.toUpperCase(),
  }).format((amount ?? 0) / 100);
}

function getTransactionStatus(amountPaid: number, refundedAmount: number) {
  if (refundedAmount > 0 && refundedAmount >= amountPaid) return "refunded";
  if (refundedAmount > 0) return "partially refunded";
  if (amountPaid > 0) return "paid";
  return "open";
}

function safeText(value: unknown) {
  return String(value ?? "")
    .replace(/[^\x20-\x7E]/g, "")
    .slice(0, 120);
}

async function createReceiptPdf({
  receiptId,
  customerEmail,
  transactionId,
  date,
  amount,
  status,
}: {
  receiptId: string;
  customerEmail: string;
  transactionId: string;
  date: string;
  amount: string;
  status: string;
}) {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const { width } = page.getSize();

  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const black = rgb(0.09, 0.09, 0.11);
  const gray = rgb(0.45, 0.45, 0.5);
  const lightGray = rgb(0.94, 0.94, 0.96);
  const border = rgb(0.84, 0.84, 0.88);
  const primary = rgb(0.05, 0.45, 0.35);

  let y = 780;

  // Header
  page.drawText("HelpexAI", {
    x: 50,
    y,
    size: 26,
    font: boldFont,
    color: black,
  });

  page.drawText("Business Knowledge Workspace", {
    x: 50,
    y: y - 18,
    size: 10,
    font: regularFont,
    color: gray,
  });

  page.drawText("Payment Receipt", {
    x: 380,
    y,
    size: 18,
    font: boldFont,
    color: black,
  });

  page.drawText(safeText(receiptId), {
    x: 380,
    y: y - 18,
    size: 9,
    font: regularFont,
    color: gray,
  });

  // Divider
  page.drawLine({
    start: { x: 50, y: 720 },
    end: { x: width - 50, y: 720 },
    thickness: 1,
    color: border,
  });

  y = 680;

  const rows = [
    ["Receipt ID", receiptId],
    ["Date", date],
    ["Customer", customerEmail],
    ["Transaction ID", transactionId],
    ["Status", status],
  ];

  for (const [label, value] of rows) {
    page.drawText(label, {
      x: 50,
      y,
      size: 11,
      font: boldFont,
      color: black,
    });

    page.drawText(safeText(value), {
      x: 190,
      y,
      size: 11,
      font: regularFont,
      color: gray,
    });

    y -= 26;
  }

  y -= 20;

  // Table header background
  page.drawRectangle({
    x: 50,
    y: y - 8,
    width: width - 100,
    height: 34,
    color: lightGray,
    borderColor: border,
    borderWidth: 1,
  });

  page.drawText("Description", {
    x: 65,
    y: y + 3,
    size: 11,
    font: boldFont,
    color: black,
  });

  page.drawText("Amount", {
    x: 465,
    y: y + 3,
    size: 11,
    font: boldFont,
    color: black,
  });

  y -= 45;

  // Table row
  page.drawRectangle({
    x: 50,
    y: y - 8,
    width: width - 100,
    height: 42,
    borderColor: border,
    borderWidth: 1,
  });

  page.drawText("HelpexAI Monthly Plan", {
    x: 65,
    y: y + 6,
    size: 11,
    font: regularFont,
    color: black,
  });

  page.drawText(safeText(amount), {
    x: 465,
    y: y + 6,
    size: 11,
    font: boldFont,
    color: black,
  });

  y -= 70;

  page.drawText("Total Paid", {
    x: 370,
    y,
    size: 14,
    font: boldFont,
    color: black,
  });

  page.drawText(safeText(amount), {
    x: 465,
    y,
    size: 14,
    font: boldFont,
    color: primary,
  });

  // Footer
  page.drawLine({
    start: { x: 50, y: 110 },
    end: { x: width - 50, y: 110 },
    thickness: 1,
    color: border,
  });

  page.drawText(
    "This receipt is generated by HelpexAI using available Creem transaction data.",
    {
      x: 50,
      y: 85,
      size: 9,
      font: regularFont,
      color: gray,
    },
  );

  page.drawText(
    "For official tax invoices or billing records, please use the Creem customer portal.",
    {
      x: 50,
      y: 70,
      size: 9,
      font: regularFont,
      color: gray,
    },
  );

  return pdfDoc.save();
}

export async function GET(
  request: Request,
  {
    params,
  }: {
    params: Promise<{ transactionId: string }>;
  },
) {
  const context = await getDocumentRequestContext();

  if (!context) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { transactionId } = await params;

  const { data: account, error: accountError } = await context.service
    .from("accounts")
    .select("creem_customer_id")
    .eq("user_id", context.user.id)
    .eq("category_slug", context.category)
    .maybeSingle();

  if (accountError) {
    return NextResponse.json(
      { error: "Could not load billing account." },
      { status: 500 },
    );
  }

  if (!account?.creem_customer_id) {
    return NextResponse.json(
      { error: "Creem customer was not found." },
      { status: 404 },
    );
  }

  const transactionsResult = await listCreemCustomerTransactions(
    account.creem_customer_id,
  );

  const transactions =
    transactionsResult.items ?? transactionsResult.data ?? [];

  const transaction = transactions.find((item) => item.id === transactionId);

  if (!transaction) {
    return NextResponse.json(
      { error: "Transaction was not found." },
      { status: 404 },
    );
  }

  const amountPaid = transaction.amount_paid ?? transaction.amount ?? 0;
  const refundedAmount = transaction.refunded_amount ?? 0;

  const pdfBytes = await createReceiptPdf({
    receiptId: `HLX-${transaction.id}`,
    customerEmail: context.user.email ?? "Customer",
    transactionId: transaction.id,
    date: formatDate(transaction.created_at),
    amount: formatAmount(amountPaid, transaction.currency ?? "USD"),
    status: getTransactionStatus(amountPaid, refundedAmount),
  });

  return new NextResponse(Buffer.from(pdfBytes), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="helpexai-receipt-${transaction.id}.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
